-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPTNO INT NOT NULL,
    DNAME VARCHAR(10),
    LOC VARCHAR(14),
    PINCODE INT(6) NOT NULL,
    PRIMARY KEY (DEPTNO)
);

-- Alter table to add a new column
ALTER TABLE DEPARTMENT ADD (PHONE VARCHAR(15));

-- Drop a column
ALTER TABLE DEPARTMENT DROP COLUMN PHONE;

-- Insert data
INSERT INTO DEPARTMENT (DEPTNO, DNAME, LOC, PINCODE) VALUES 
(1, 'HR', 'SANGLI', 10001),
(2, 'IT', 'JALGAON', 90001),
(3, 'Finance', 'KOLHAPUR', 94101);

-- Update data
UPDATE DEPARTMENT SET LOC = 'JALGAON' WHERE DEPTNO = 3;

-- Delete data
DELETE FROM DEPARTMENT WHERE DEPTNO = 3;

-- Select data
SELECT * FROM DEPARTMENT;

-- Drop the table
DROP TABLE DEPARTMENT;